Repository OpenDevicePartnership/embassy-imxrt, pull requests merged in 2025-09, with the labels that each got.

#481 finalize transition to crates.io
  Cargo.lock
  Cargo.toml
  examples/rt633/Cargo.lock
  examples/rt633/Cargo.toml
  examples/rt685s-evk-performance-tracing/Cargo.lock
  examples/rt685s-evk-performance-tracing/Cargo.toml
  examples/rt685s-evk/Cargo.lock
  examples/rt685s-evk/Cargo.toml
  supply-chain/audits.toml
  supply-chain/config.toml
Labels: bug, BREAKING CHANGE, cargo update, cargo vet

#483 Remove dependency on defmt from embassy-imxrt
  Cargo.toml
Labels: dependencies

#482 Add SPI driver
  examples/rt685s-evk/Cargo.lock
  examples/rt685s-evk/Cargo.toml
  examples/rt685s-evk/src/bin/spi-async.rs
  examples/rt685s-evk/src/bin/spi-loopback.rs
  examples/rt685s-evk/src/bin/spi.rs
  src/lib.rs
  src/spi.rs
Labels: enhancement

#495 Fix intermittent ci failure
  .github/workflows/check.yml
  ci.sh
Labels: enhancement
