Repository OpenDevicePartnership/embassy-imxrt, pull requests merged in 2025-05, with the labels that each got.

#404 Update workflows to add comment to PR on cargo vet failure
  .github/workflows/cargo-vet-pr-comment.yml
  .github/workflows/cargo-vet.yml
  .github/workflows/check.yml
  .github/workflows/commit-list.yml
  supply-chain/README.md
Labels: enhancement, github_actions

#417 Flexspi Cleanup
  examples/rt685s-evk/src/bin/flexspi-storage-service.rs
  src/flexspi/mod.rs
  src/flexspi/nor.rs
  src/lib.rs
Labels: nvm

#413 Fix time conversion bug in Datetime code
  src/time_driver.rs
Labels: core hal

#414 check.yml: remove per commit checking
  .github/workflows/check.yml
Labels: github_actions, cargo vet

#420 Pull audits from rust-crate-audits
  supply-chain/README.md
  supply-chain/config.toml
  supply-chain/imports.lock
Labels: enhancement, cargo vet

#419 Update cargo vet to run on final commit only
  .github/workflows/cargo-vet.yml
  .github/workflows/commit-list.yml
Labels: enhancement, github_actions

#421 Add support for using the OS Timer0 as time source
  .github/workflows/check.yml
  Cargo.lock
  Cargo.toml
  examples/rt633/Cargo.lock
  examples/rt633/Cargo.toml
  examples/rt685s-evk/Cargo.lock
  examples/rt685s-evk/Cargo.toml
  examples/rt685s-evk/src/bin/rtc-time.rs
  src/clocks.rs
  src/lib.rs
  src/rtc.rs
  src/time_driver/mod.rs
  src/time_driver/ostimer.rs
  src/time_driver/rtc.rs
Labels: bug, enhancement, cargo vet

#423 Move cargo-hack to a script
  .github/workflows/check.yml
  ci.sh
Labels: enhancement, github_actions

#428 Update and vet mimxrt633s-pac
  Cargo.lock
  supply-chain/audits.toml
  supply-chain/config.toml
Labels: dependencies

#431 timer: ostimer: wait for match write ready
  src/time_driver/ostimer.rs
Labels: bug

#433 Calibrate delay loop clocks
  src/clocks.rs
Labels: bug

#432 Add a simple button example
  examples/rt685s-evk/src/bin/button.rs
Labels: enhancement

#435 Add codeowners for cargo vet, new crate policies and update README
  CODEOWNERS
  supply-chain/README.md
  supply-chain/config.toml
Labels: documentation, enhancement

#438 examples: fix sha256-async hang in release mode
  src/hashcrypt/hasher.rs
Labels: bug

#434 Add simple keyboard example
  examples/rt685s-evk/Cargo.lock
  examples/rt685s-evk/Cargo.toml
  examples/rt685s-evk/src/bin/keyboard.rs
Labels: enhancement
