Repository OpenDevicePartnership/embassy-imxrt, pull requests merged in 2025-02, with the labels that each got.

#278 Draft initial project documents
  CODE_OF_CONDUCT.md
  CONTRIBUTING.md
  LICENSE
  SECURITY.md
Labels: dependencies

#279 Fixed barrier instruction sequence
  src/flash.rs
Labels: bug

#280 i2c master: use ondrop to recover if address sending fails and check arbitration loss as well after sending of address
  src/i2c/master.rs
Labels: bug, enhancement

#271 Add minimal support for MIMXRT633S
  .github/workflows/check.yml
  .github/workflows/nostd.yml
  Cargo.toml
  examples/rt685s-evk/Cargo.toml
  src/chips/mimxrt633s.rs
  src/chips/mimxrt685s.rs
  src/i2c/master.rs
  src/i2c/slave.rs
  src/lib.rs
  src/pwm.rs
  src/timer.rs
  src/uart.rs
Labels: enhancement, github_actions

#308 Fix address nack race condition
  examples/rt685s-evk/src/bin/i2c-master-async.rs
  src/i2c/master.rs
Labels: bug

#307 Add espi driver
  Cargo.toml
  examples/rt633/.cargo/config.toml
  examples/rt633/.gitignore
  examples/rt633/Cargo.toml
  examples/rt633/README.md
  examples/rt633/build.rs
  examples/rt633/memory.x
  examples/rt633/rt633.yaml
  examples/rt633/rust-toolchain.toml
  examples/rt633/rustfmt.toml
  examples/rt633/src/bin/espi.rs
  examples/rt633/src/lib.rs
  src/clocks.rs
  src/espi.rs
  src/lib.rs
Labels: enhancement

#313 [BREAKING] Update rt633.yaml
  examples/rt633/rt633.yaml
Labels: enhancement

#315 crc: make Config fields public & use new WR_DATA size accessors
  Cargo.toml
  examples/rt685s-evk/src/bin/crc.rs
  src/crc.rs
Labels: bug

#318 rolling: allow rolling to work again
  .github/workflows/rolling.yml
Labels: bug, github_actions

#316 crc: use more standard names for configuration parameters
  examples/rt685s-evk/src/bin/crc.rs
  src/crc.rs
Labels: enhancement

#324 Espi updates
  src/espi.rs
Labels: bug, enhancement

#328 improve crate documentation
  Cargo.toml
  README.md
Labels: documentation

#330 Add benchmarking examples using DWT/systick/GPIO pin toggling
  examples/rt685s-evk/src/bin/benchmarking-gpio.rs
  examples/rt685s-evk/src/bin/benchmarking-system-peripheral.rs
Labels: documentation, enhancement

#332 Optimize i2c read by handling the last byte manually
  src/i2c/master.rs
Labels: enhancement
