Repository OpenDevicePartnership/embassy-imxrt, pull requests merged in 2025-03, with the labels that each got.

#323 Update CaptureTimer to calculate fan speed
  examples/rt685s-evk/src/bin/timer.rs
  src/timer.rs
Labels: enhancement

#339 espi: set SRST bit on port complete
  src/espi.rs
Labels: bug

#340 deny.toml: add exception for paste
  deny.toml
Labels: bug

#341 Espi VWires
  Cargo.toml
  examples/rt633/src/bin/espi.rs
  src/espi.rs
  src/timer.rs
Labels: enhancement, rust

#321 Add support for FC14 SPI (Untested) and FC15 I2C
  src/chips/mimxrt633s.rs
  src/chips/mimxrt685s.rs
  src/flexcomm.rs
  src/i2c/mod.rs
  src/iopctl.rs
Labels: enhancement

#333 Add NoDma I2C master async bus implementation
  examples/rt685s-evk/src/bin/dma-mem.rs
  src/dma/mod.rs
  src/hashcrypt/mod.rs
  src/i2c/master.rs
  src/i2c/mod.rs
  src/i2c/slave.rs
  src/uart.rs
Labels: enhancement

#344 eSPI mailbox split
  examples/rt633/src/bin/espi.rs
  src/espi.rs
Labels: enhancement

#359 Flexcomm minimal cleanup
  src/flexcomm.rs
Labels: enhancement

#360 Fixed recent regressions caused by upstream changes
  src/adc.rs
  src/crc.rs
  src/dma/mod.rs
  src/espi.rs
  src/flexcomm.rs
  src/gpio.rs
  src/hashcrypt/mod.rs
  src/i2c/master.rs
  src/i2c/mod.rs
  src/i2c/slave.rs
  src/lib.rs
  src/pwm.rs
  src/rng.rs
  src/time_driver.rs
  src/timer.rs
  src/uart.rs
  src/wwdt.rs
Labels: bug, BREAKING CHANGE, cargo update

#358 Fix cannot set UART baudrate to those value other than 115200 issue
  src/uart.rs
Labels: bug
