Repository OpenDevicePartnership/embassy-imxrt, pull requests merged in 2025-04, with the labels that each got.

#366 Move waker registrations PRIOR to condition checking
  src/dma/channel.rs
  src/espi.rs
  src/i2c/master.rs
  src/rng.rs
  src/uart.rs
Labels: bug

#365 i2c slave: relax state machine restriction
  src/i2c/slave.rs
Labels: bug, core hal

#368 Add UART drop guards
  src/uart.rs
Labels: bug, enhancement

#369 Fix UART CTS
  src/uart.rs
Labels: bug

#371 Added support for OOB and removed SRST added wait_for_plat_reset
  src/espi.rs
Labels: enhancement

#373 Limit unsafe scope (and other cleanups)
  src/clocks.rs
Labels: enhancement, core hal

#370 Ensure I2C blocking slave polling stops on deselect as well.
  src/i2c/slave.rs
Labels: bug

#387 Update FCB, enable debug info, replace tabs with spaces in memory.x
  examples/rt685s-evk/Cargo.lock
  examples/rt685s-evk/Cargo.toml
  examples/rt685s-evk/memory.x
Labels: enhancement

#374 Cargo vet init
  .github/workflows/check.yml
  supply-chain/README.md
  supply-chain/audits.toml
  supply-chain/config.toml
  supply-chain/imports.lock
Labels: enhancement, github_actions

#391 Update actions to use cargo.lock for dependencies
  .github/workflows/check.yml
  .github/workflows/nostd.yml
Labels: enhancement

#390 Add CRC reconfigure_new function to reuse object with new algorithm
  src/crc.rs
Labels: enhancement

#400 Avoid vetting embassy dependencies pulled from GitHub
  supply-chain/config.toml
Labels: enhancement
